### ISSUE TITLE
psutil/phymem_usage() compatibility problems

### ISSUE THREAD

**Issue by affeder** [terhorst/EandR-timeseries#3]
It seems like phymem_usage() in psutil is deprecated in 4.0.0 (maybe after 0.6.0?). I could only get the example working after back-installing psutil 0.5.0. It would be nice to update the documentation for others encountering issues related to phymem_usage.

**Comment by johnbarton** [comment]
This function has now been replaced by virtual_memory(), apparently. Replacing phymem_usage() with virtual_memory() allows the example to execute successfully with the current version (5.3.1 as of this post).
